version: "3.9"
services:
  grafana:
    image: grafana/grafana:9.2.6
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 3000:3000

  redis:
    image: bitnami/redis:7.0.5
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=my_master_password
  
  prometheus:
    image: prom/prometheus:v2.40.3
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      
  redis-exporter:
    image: oliver006/redis_exporter:v1.45.0
    ports:
      - 9121:9121
    environment:
      REDIS_ADDR: "redis:6379"
      REDIS_USER: null
      REDIS_PASSWORD: my_master_password
    links:
      - redis
      - prometheus